### PR TITLE
- add support for scene tags, regions and subtitle tags.

### PR DESCRIPTION
**Pull request by jxs**
Hi there,
needed to add support for scene tags in my use case. If the release had a scene tag like REMASTERED, the title was being made of only that tag.
Also replaced dots with spaces because in my use case the release name is always made of dots instead of spaces, but noticed a test was failing because "Mr. Robot" dot was being removed, I updated the test, but I can understand it doesn't fit your needs in this way, if you want I can rebase and remove that change for your case

### CODE REVIEW

**Comment by dogamak** [comment]
Hi, and thanks for the PR.

The logic for detecting the new fields seems fine and I am fine with merging this for those parts. However considering `.`, and only `.`, to denote whitespace seems a bit inflexible and specific to your needs.

One way to handle whitespace in the title would be to detect if the part of the title assumed to contain the title contains any whitespace as-is and depending on that replacing a different set of symbols with whitespace. Any whitespace should be reduced to a single space after processing the title, so that the current `Mr__Robot` would become `Mr_Robot`.

Filenames that contain no spaces could be handled by replacing all non-alphanumeric characters with whitespace while filenames that contain whitespace could allow some symbols commonly appearing in titles, such as `?`, `!`, `&` and `:`, or maybe even all symbols, trusting the user to have done proper formatting.

Would you be willing to make these changes or should I merge this as-is? I can make these changes myself too if you don't have a need for them.

**Comment by jxs** [comment]
yes, i'll make the changes no worries :) give me just a couple of days

**Comment by jxs** [comment]
turns out I don't need the `.` and can use whitespace as you use, do you still need those changes?
thanks

**Comment by dogamak** [comment]
Well, I don't strictly need the changes as I am no longer using this crate myself. However, I think these changes would avoid making assumptions about the input and make the crate suitable for larger number of users and use-cases.

If you don't need these changes or don't want to implement them, I have no problem doing it myself. In order to do that, in the way that makes the most sense to me, I would need push permissions to your forked repository so that I can commit directly to this pull request.

**Comment by jxs** [comment]
yeah, you are right, I don't need them but they definitely make the crate suitable for larger a audience. I changed the PR to only add the support for scene tags, do you still need push permissions from the forked repository? (it's on the same state as the PR)
thanks!

**Pull request closed without merging**
